maps/de_zook.res
maps/de_zook.txt
overviews/de_zook.bmp
overviews/de_zook.txt
gfx/env/trainyardup.tga
gfx/env/trainyarddn.tga
gfx/env/trainyardlf.tga
gfx/env/trainyardrt.tga
gfx/env/trainyardft.tga
gfx/env/trainyardbk.tga
sprites/glow01.spr
sprites/glow02.spr
